on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Bundle files and create a release
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Bundle and release
        shell: bash
        run: |
          node action/dist/index.js ${{ secrets.GITHUB_TOKEN }}
